add video workflow

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -52,13 +52,13 @@ ARG UNAME=ComfyUI
 COPY ./requirements_comfyui /tmp/requirements
 RUN set -e; \
     for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
-        pip install --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
+        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
     done \
     && rm -rf /tmp/requirements
 
 USER $UNAME
 EXPOSE 8188
-CMD ["python3", "/home/ComfyUI/main.py", "--listen", "--port", "8188"]
+CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
 
 ############################################################################################
 
@@ -69,13 +69,13 @@ ARG UNAME=ComfyUI
 COPY ./requirements_ootd /tmp/requirements
 RUN set -e; \
     for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
-        pip install --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
+        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
     done \
     && rm -rf /tmp/requirements
 
 USER $UNAME
 EXPOSE 8188
-CMD ["python3", "/home/ComfyUI/main.py", "--listen", "--port", "8188"]
+CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
 
 ###########################################################################################
 
@@ -88,19 +88,19 @@ RUN pip install --no-cache-dir kiui
 COPY ./requirements_3dpack /tmp/requirements
 RUN set -e; \
     for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
-        pip install --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
+        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
     done \
     && rm -rf /tmp/requirements
 
 COPY ./requirements_3dpack.txt /tmp
 RUN set -e; \
-    pip install --no-cache-dir -r /tmp/requirements_3dpack.txt || exit 1 \
+    pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r /tmp/requirements_3dpack.txt || exit 1 \
     && rm -rf /tmp/requirements_3dpack.txt
 
 
 USER $UNAME
 EXPOSE 8188
-CMD ["python3", "/home/ComfyUI/main.py", "--listen", "--port", "8188"]
+CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
 
 
 ############################################################################################
@@ -112,10 +112,45 @@ ARG UNAME=ComfyUI
 COPY ./requirements_flowty /tmp/requirements
 RUN set -e; \
     for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
-        pip install --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
+        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
     done \
     && rm -rf /tmp/requirements
 
 USER $UNAME
 EXPOSE 8188
-CMD ["python3", "/home/ComfyUI/main.py", "--listen", "--port", "8188"]
+CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
+
+############################################################################################
+
+From base as comfyui-video
+
+ARG UNAME=ComfyUI
+
+COPY ./requirements_video /tmp/requirements
+RUN set -e; \
+    for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
+        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
+    done \
+    && rm -rf /tmp/requirements
+
+USER $UNAME
+EXPOSE 8188
+CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
+
+############################################################################################
+
+From comfyui-video as comfyui-controlnet-video
+
+ARG UNAME=ComfyUI
+
+COPY ./requirements_controlnet_video /tmp/requirements
+RUN set -e; \
+    for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
+        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
+    done
+
+RUN pip install --no-cache-dir fvcore omegaconf
+
+USER $UNAME
+EXPOSE 8188
+CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
