fix

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -33,124 +33,70 @@ RUN \
     && pip config set global.index-url $PIP_INDEX \
     && pip install --no-cache-dir torch xformers --index-url https://download.pytorch.org/whl/cu121 
 
+RUN pip install -i $PIP_INDEX --default-timeout=100 --no-cache-dir opencv-python-headless --extra-index-url https://download.pytorch.org/whl/cu121
 
 COPY ./requirements_base /tmp/requirements_base
 RUN find /tmp/requirements_base -name requirements.txt \
-    && find /tmp/requirements_base -name requirements.txt -exec pip install --no-cache-dir -r {} \; \
+    && find /tmp/requirements_base -name requirements.txt -exec pip install -i $PIP_INDEX --default-timeout=100 --no-cache-dir -r {} \; \
     && rm -rf /tmp/requirements_base
 
-RUN groupadd -g $GID -o $UNAME
-RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
-WORKDIR /home/ComfyUI
+RUN groupadd -g $GID -o $UNAME && useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME \
+    && mkdir -p /home/$UNAME/.cache && chmod 777 /home/$UNAME/.cache
+
+WORKDIR /home/ComfyUI/app
+
+USER $UNAME
+EXPOSE 8188
+CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
 
 ############################################################################################
 
 From base as comfyui-comfyui
 
-ARG UNAME=ComfyUI
-
 COPY ./requirements_comfyui /tmp/requirements
-RUN set -e; \
+RUN pip install --no-cache-dir --upgrade -i $PIP_INDEX pip && pip config set global.index-url $PIP_INDEX && \
+    set -e; \
     for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
-        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
-    done \
-    && rm -rf /tmp/requirements
+        pip install --default-timeout=100 --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
+    done
 
-USER $UNAME
-EXPOSE 8188
+RUN pip install  -i $PIP_INDEX --default-timeout=100 --no-cache-dir fvcore omegaconf ultralytics dashscope pytorch_lightning --extra-index-url https://download.pytorch.org/whl/cu121
+
+ENV PATH="$HOME/.local/bin:$PATH"
+
 CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
-
 ############################################################################################
 
 From base as comfyui-ootd
 
-ARG UNAME=ComfyUI
-
 COPY ./requirements_ootd /tmp/requirements
-RUN set -e; \
+RUN pip install --no-cache-dir --upgrade -i $PIP_INDEX pip && pip config set global.index-url $PIP_INDEX && \
+    set -e; \
     for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
-        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
-    done \
-    && rm -rf /tmp/requirements
-
-USER $UNAME
-EXPOSE 8188
-CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
+        pip install --default-timeout=100 --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
+    done
 
 ###########################################################################################
 
 From base as comfyui-3dpack
 
-ARG UNAME=ComfyUI
 ARG TORCH_CUDA_ARCH_LIST='7.5;8.0;8.6;8.9;9.0+PTX'
-RUN pip install --no-cache-dir kiui
+RUN pip install --no-cache-dir -i $PIP_INDEX kiui
 
 COPY ./requirements_3dpack /tmp/requirements
-RUN set -e; \
-    for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
-        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
-    done \
-    && rm -rf /tmp/requirements
-
-COPY ./requirements_3dpack.txt /tmp
-RUN set -e; \
-    pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r /tmp/requirements_3dpack.txt || exit 1 \
-    && rm -rf /tmp/requirements_3dpack.txt
-
-
-USER $UNAME
-EXPOSE 8188
-CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
-
-
-############################################################################################
-
-From base as comfyui-flowty
-
-ARG UNAME=ComfyUI
-
-COPY ./requirements_flowty /tmp/requirements
-RUN set -e; \
-    for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
-        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
-    done \
-    && rm -rf /tmp/requirements
-
-USER $UNAME
-EXPOSE 8188
-CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
-
-############################################################################################
-
-From base as comfyui-video
-
-ARG UNAME=ComfyUI
-
-COPY ./requirements_video /tmp/requirements
-RUN set -e; \
-    for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
-        pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
-    done \
-    && rm -rf /tmp/requirements
-
-USER $UNAME
-EXPOSE 8188
-CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
-
-############################################################################################
-
-From comfyui-video as comfyui-controlnet-video
-
-ARG UNAME=ComfyUI
-
-COPY ./requirements_controlnet_video /tmp/requirements
-RUN set -e; \
+RUN pip install --no-cache-dir --upgrade -i $PIP_INDEX pip && pip config set global.index-url $PIP_INDEX && \
+    set -e; \
     for file in $(find /tmp/requirements -type f -name 'requirements*.txt'); do \
         pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r "$file" || { echo "Failed to install dependencies from $file"; exit 1; }; \
     done
 
-RUN pip install --no-cache-dir fvcore omegaconf
+COPY ./requirements_3dpack.txt /tmp
+RUN \
+    set -e; \
+    pip install --extra-index-url https://download.pytorch.org/whl/cu121 --no-cache-dir -r /tmp/requirements_3dpack.txt || exit 1 
 
-USER $UNAME
-EXPOSE 8188
-CMD ["python3", "/home/ComfyUI/app/main.py", "--listen", "--port", "8188"]
+RUN apt -o Acquire::ForceIPv4=true update && apt -o Acquire::ForceIPv4=true install -y ninja-build
+
+RUN pip install --no-cache-dir -i $PIP_INDEX rembg Ninja
+############################################################################################
+
